site_name: aepolicht
site_author: Alexander Policht
site_description: Personal projects page.

theme: 'material'

# repo_name: 'GitHub'
# repo_url: 'https://aepolicht.github.io'

pages:
- Home: 'index.md'
- Projects: 'projects.md'
- MoboNet: 'mobonet.md'
- About: 'about.md'
